author           = Dragonop
description      = This mod introduces the Claycrafter, which converts Compressed Dirt to Clay using Glasses of Water.
depends          = vessels, default
name             = claycrafter
optional_depends = moreblocks, appliances, pipeworks, technic, ia_util, farming
title            = IA Claycrafter
